### ISSUE TITLE
[UI] Main content overflow

### ISSUE THREAD

**Issue by abellion** [swarmpit/swarmpit#461]
On my 13" screen, the main content of some pages overflows.

![image](https://user-images.githubusercontent.com/9916488/73489440-e133ef80-43aa-11ea-8f39-2d01bb779f24.png)

If I zoom out just a little bit the UI looks normal. I think the issue comes from a responsive breakpoint which would need a small tweak.

I saw the issue on the following pages :
- `/tasks/XXX`
- `/networks/XXX`
- `/volumes/XXX`
- `/users/XXX`
- `/configs/XXX`
- `/configs/create`
... and so on

Thanks for Swarmpit.

**Comment by nohaapav** [comment]
This issue is caused by container component not breakpoints. Thanks for reporting though.

**Comment by nohaapav** [comment]
@abellion Fixed in master.

**Comment by abellion** [comment]
It looks better but I think there is still an issue :

Network page :

![image](https://user-images.githubusercontent.com/9916488/73551976-ae8c0480-4447-11ea-8337-07203f571371.png)

Dashboard page :

![image](https://user-images.githubusercontent.com/9916488/73551987-b0ee5e80-4447-11ea-9494-5038a2e9b174.png)

As you can see, the spacing I highlighted is not the same.

**Comment by nohaapav** [comment]
Looks same on my 13" simulator screen but might be the case .. dashboard is not using container wrapper, it's always fullscreen. Rest is wrapped by container fitting size based on breakpoint to avoid full width on XL screens ..

**Comment by AlexGustafsson** [comment]
This seems to be an issue for several sizes, which I'm trying to highlight in the gif below.

![swarmpit](https://user-images.githubusercontent.com/14974112/85231912-6c199300-b3fb-11ea-9571-91adfb07fe43.gif)

As can be seen, there is a large gap between the breakpoints where the content correctly fits to the screen. There might also be some sort of bug here, as when the screen size is being increased, the site seems to be correctly responsive - but not when the screen is getting smaller.

The browser is Safari 13.1 on macOS. The version of swarmpit is 1.9.

**Comment by nohaapav** [comment]
@AlexGustafsson Looks like plotly is somehow breaking the layout ..
